const GREY_BLUE: string = '#304666'
const DARK_BLUE: string = '#1e3250'
const DARK_GREY = '#4f4f4f'
const VERY_DARK_GREY = '#242424'
const DARKER_BLUE = '#0d78d4'
const DARKER_GREEN: string = '#7ca229'
const DARKER_GREY = '#808080'
const EXTRA_LIGHT_GREY: string = '#fbfcfc'
const VERY_LIGHT_GREY: string = '#f4f6f8'
const GREY: string = '#C0C0C0'
const LIGHT_BLUISH_GREY: string = '#e2e8ef'
const MID_BLUISH_GREY: string = '#ccd5e2'
const BLUISH_GREY: string = '#8d9aad'
const DARK_BLUISH_GREY: string = '#697e9e'
const LIGHT_BLUE: string = '#9ad1ff'
const LIGHT_GREEN = '#ebf4d7'
const BLUE: string = '#3da6ff'
const GREEN: string = '#9fcc3e'
const RED: string = '#FF6060'
const DARKER_RED: string = '#de3c3c'
const ORANGE: string = '#ff9c00'
const DARK_PURPLE: string = '#8191f3'
const GOOGLE: string = '#d34836'
const FACEBOOK: string = '#3b5998'
const MESSENGER: string = '#0078FF'
const TWITTER: string = '#1da1f2'
const INSTAGRAM: string = '#c32aa3'
const PINTEREST: string = '#bd081c'
const LINKEDIN: string = '#007bb5'
const SIDEBAR_HOVER: string = '#bebebe'
const SIDEBAR_BACKGROUND: string = '#eaeaea'
const SIDEBAR_ICON: string = '#9b9b9b'
const DROPZONE: string = '#d1e7ad'
const TOUR_FOOTER: string = '#5A5A5A'

export const themeColors = {
  ACTIONBAR_BACKGROUND: EXTRA_LIGHT_GREY,
  ALERT: RED,
  ALERT_HOVER: DARKER_RED,
  BACKGROUND: VERY_LIGHT_GREY,
  BLOCK_OF_TEXT: DARKER_GREY,
  BLUE,
  BORDER: LIGHT_BLUISH_GREY,
  BUBBLE_BACKGROUND: DARK_BLUE,
  BUTTON_BACKGROUND: '#fff',
  BUTTON_BORDER: LIGHT_BLUISH_GREY,
  BUTTON_BORDER_HOVER: GREEN,
  BUTTON_ICON: MID_BLUISH_GREY,
  BUTTON_ICON_HOVER: GREEN,
  BUTTON_INFO_HOVER: DARKER_BLUE,
  CALENDAR_RANGE_LIMIT: GREEN,
  CALENDAR_WITHIN_RANGE: LIGHT_GREEN,
  COPYRIGHT: DARK_GREY,
  DARK_BLUE,
  DARK_GREY,
  DARK_PURPLE,
  DARKER_GREEN,
  DARKER_GREY,
  DROPZONE,
  EXTRA_LIGHT_GREY,
  FACEBOOK,
  FIELD_TEXT: GREY_BLUE,
  GOOGLE,
  GREEN,
  GREY,
  HEADER: DARK_BLUISH_GREY,
  HEADER_BACKGROUND: '#fff',
  HEADER_BORDER: GREY,
  ICON_HOVER: GREEN,
  ICON_UNSELECTED: MID_BLUISH_GREY,
  IMAGE_BACKGROUND: EXTRA_LIGHT_GREY,
  INFO_BORDER: MID_BLUISH_GREY,
  INSTAGRAM,
  LABEL_REVERSE_TEXT: '#fff',
  LABEL_TEXT: BLUISH_GREY,
  LABEL_TEXT_HOVER: GREY_BLUE,
  LIGHT_BLUE,
  LIGHT_BLUISH_GREY,
  LINKEDIN,
  MAP_PIN: GREEN,
  MESSENGER,
  MODAL_BACKGROUND: LIGHT_BLUISH_GREY,
  MODAL_BORDER: GREY,
  OK: GREEN,
  ORANGE,
  PACKAGE_CARD: GREEN,
  PINTEREST,
  PUBLIC_MAIN_FOOTER: EXTRA_LIGHT_GREY,
  PUBLIC_NAVIGATION_LINK: DARKER_GREY,
  PUBLIC_NAVIGATION_LINK_HOVER: GREY,
  PUBLIC_SECONDARY_FOOTER: VERY_DARK_GREY,
  SECONDARY_NAVIGATION_LINK: DARK_BLUISH_GREY,
  SELECTABLE_PHOTO_SIDEBAR_BG: SIDEBAR_HOVER,
  SIDEBAR_BACKGROUND,
  SIDEBAR_ICON,
  SIDEBAR_ICON_HOVER: '#fff',
  SIDEBAR_ITEM_BACKGROUND_HOVER: SIDEBAR_HOVER,
  STATUS_ACTIVE: GREEN,
  STATUS_INACTIVE: GREY,
  STATUS_MEDIA_ONLY: BLUE,
  STATUS_OVERDUE: RED,
  STATUS_PENDING: ORANGE,
  STATUS_PUBLISHED: GREEN,
  STATUS_SCHEDULED: GREEN,
  STATUS_SOLD: RED,
  STATUS_UNASSIGNED: BLUE,
  STATUS_UNPUBLISHED: GREY,
  STATUS_UNSCHEDULED: ORANGE,
  SUSPENDED: MID_BLUISH_GREY,
  TEXT: MID_BLUISH_GREY,
  TEXT_SELECTED: GREY_BLUE,
  TEXT_UNSELECTED: MID_BLUISH_GREY,
  TOUR_FOOTER,
  TWITTER,
  WEB_BACKGROUND: BLUE,
  WEB_BORDER: LIGHT_BLUE
}
